### ISSUE TITLE
Optimizing SurfaceFinder.cpp  class by implementing atomic methods, improving code readability, adding documentation for further development, and preparing for unit testing and parallelization

### ISSUE THREAD

**Issue by hmehryar** [JETSCAPE/JETSCAPE#211]
### Todos
-  implementing atomic methods for business code (Short and testable helper and business functions), 
- improving code readability (using standard C++ data structures, and code conventions), 
- adding documentation for further development (adding Doxygen documentation into the header file), and 
- preparing for unit testing and parallelization

- [x] https://github.com/JETSCAPE/JETSCAPE/issues/212
- [x] https://github.com/JETSCAPE/JETSCAPE/issues/213
- [x] https://github.com/JETSCAPE/JETSCAPE/issues/215
- [x] https://github.com/JETSCAPE/JETSCAPE/issues/216
- [x] https://github.com/JETSCAPE/JETSCAPE/issues/219

**Comment by latessa** [comment]
These enhancements are implemented in the JETSCAPE 4.0 RC.
