### ISSUE TITLE
Upgrades for the ThermalPartonSampler class

### ISSUE THREAD

**Issue by Hendrik1704** [JETSCAPE/JETSCAPE#220]
### Enhancement Overview

**Todos**
- [ ] Refactoring of the ThermalPartonSampler class (smaller functions, less code duplication, ...)
- [ ] Upgrade the integration method using an analytical expansion of the integral over the Fermi-Dirac distribution
- [ ] Implement unit tests
- [ ] Parallelization with OpenMP

**Comment by latessa** [comment]
This is now implemented in the JETSCAPE 4.0-RC.
